; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp8266

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.f_cpu = 160000000L
board_build.ldscript = eagle.flash.4m.ld
build_flags = 
    -O3
    -DESP8266_BOARD
monitor_speed = 115200

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -O3
monitor_speed = 115200
board_build.partitions = partitions.csv

